### ISSUE TITLE
será que dá pra colocar isso em movimento?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#13]
<img width="210" alt="image" src="https://github.com/user-attachments/assets/aefa86fd-c570-4b4a-9180-039a023cc2b0">

**Comment by mauricio-azevedo** [comment]
só se 1. a imagem não tiver fundo OU 2. a cor de fundo do container for igual a cor do fundo da imagem

**Comment by jacguima** [comment]
container? como assim?

ela não tem fundo!! eu que coloquei! posso compartilhar o negocio do canva com você e discutimos juntos :)

**Comment by jacguima** [comment]
<img width="230" alt="image" src="https://github.com/user-attachments/assets/77128612-fb15-489e-b1db-9a1cbe3249f2">
que

**Comment by jacguima** [comment]
<img width="230" alt="image" src="https://github.com/user-attachments/assets/37beba05-7f8a-4c51-b319-c75d6a790fbc">
queria animar todos esses 
<img width="167" alt="image" src="https://github.com/user-attachments/assets/d17ce028-e179-4b1b-ad54-9c88122c804f">
