### ISSUE TITLE
essa imagem ta meio zuada, o que acha?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#19]
<img width="416" alt="image" src="https://github.com/user-attachments/assets/2cde973c-5155-4fdd-9164-23c6f270c068">
posso te mandar uma nova pelo email! na vdd acho que já ta lá!

**Comment by mauricio-azevedo** [comment]
Se isso vier do Canva, me manda o projeto pra eu fazer o download sem fundo (recortada exatamente no celular). Fica mais fácil de posicionar a imagem. Se não tiver como, pode deixar que eu recorto aqui, só fica menos exato.

**Comment by jacguima** [comment]
ok.
link mobile:
https://www.canva.com/design/DAGJXZotD0I/GU9z4tE1JjlJF3-QC0JdGw/edit?utm_content=DAGJXZotD0I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

link desktop:
https://www.canva.com/design/DAGIEaL61LE/pvTBbHFNncqrl_dCjFArVQ/edit?utm_content=DAGIEaL61LE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
