### ISSUE TITLE
ficou ótimo, arrasou!! e o que acha dele também mexer quando passar o mouse por cima?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#20]
<img width="88" alt="image" src="https://github.com/user-attachments/assets/eb35fb98-f75d-4e43-bdbe-c8cbe5463ad1">

**Comment by mauricio-azevedo** [comment]
Mexer como? Aumentar/diminuir?

**Comment by jacguima** [comment]
sim.
