### ISSUE TITLE
o que acha... fica melhor "opiniões" ou "depoimentos"?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#21]
<img width="646" alt="image" src="https://github.com/user-attachments/assets/39ac0b01-9d2a-4324-b8a6-32f26fbab305">

**Comment by mauricio-azevedo** [comment]
"Avaliações"

**Comment by jacguima** [comment]
Não é um produto, ou uma comida. É um serviço humanizado, é uma psicoterapia. Melhor **depoimentos**.

**Comment by mauricio-azevedo** [comment]
Faz sentido. Seguindo essa linha de raciocínio, talvez seja boa ideia tirar as estrelinhas.

**Comment by mauricio-azevedo** [comment]
A Isabela Boscov faz umas reviews no Letterboxd que são quase livros mas ela muitas vezes não avalia com estrelas, eu sinto uma vibe muito profissional nisso, por algum motivo.

**Comment by jacguima** [comment]
então tira elas.

**Comment by jacguima** [comment]
ou diminui de tamanho e deixa cinza?

**Comment by jacguima** [comment]
ou podemos add isso tbm, sl 
<img width="863" alt="image" src="https://github.com/user-attachments/assets/b904cf4b-80b7-4f56-974a-6ce824e6552f">

**Comment by jacguima** [comment]
<img width="633" alt="image" src="https://github.com/user-attachments/assets/17534df7-7197-49aa-b93b-589609f92a88">
quanto as avaliações podemos deixar "depoimentos" e diminui o tamanho das estrelas pra ficar mais de boas
<img width="166" alt="image" src="https://github.com/user-attachments/assets/608d837e-ecad-4520-b870-402b8558e063">
