### ISSUE TITLE
por alguma razão louca e maravilhosa os outros ficaram alinhadinhos às perguntas :) o que acha de colocarmos essa resposta centralizada no quadrado cinza? ao invés de ficar no canto esquerdo?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#22]
<img width="353" alt="image" src="https://github.com/user-attachments/assets/c83c2601-347b-4f28-a8bc-61b135fe09ce">
<img width="509" alt="image" src="https://github.com/user-attachments/assets/8dd18d35-e143-4fdc-a0e7-0ffa4c9709f5">

**Comment by mauricio-azevedo** [comment]
Na verdade nenhum tá alinhado ao centro, eles tão justificados. Como esse último só tem uma linha, o "justificado" não faz efeito. Então vou deixar todos centralizados (os outros vão ficar um pouco diferentes).

**Comment by jacguima** [comment]
beleza, então deixa do jeito que ta. Centralizado fica feio, valeu.
