### ISSUE TITLE
essa logo ta com um fundo estranho, meio chiado

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#23]
<img width="358" alt="image" src="https://github.com/user-attachments/assets/1d9e60fa-b7be-43ee-a5c3-b6d0515094e7">

**Comment by mauricio-azevedo** [comment]
Me manda o projeto dessa logo no Canva, que eu faço o download com fundo transparente certinho. Tô no teste gratuito de 14 dias.

**Comment by jacguima** [comment]
ok. 
link mobile:
https://www.canva.com/design/DAGJXZotD0I/GU9z4tE1JjlJF3-QC0JdGw/edit?utm_content=DAGJXZotD0I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

link desktop:
https://www.canva.com/design/DAGIEaL61LE/pvTBbHFNncqrl_dCjFArVQ/edit?utm_content=DAGIEaL61LE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
