### ISSUE TITLE
Podemos fazer igual a esse?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#25]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/6d516a0c-6e73-4ecf-9591-1fc9d7dad450">
https://www.michelymanzoli.com.br/#sobremim

**Comment by mauricio-azevedo** [comment]
Me mostra onde e como, exatamente.

**Comment by jacguima** [comment]
beleza. vou montar e te mando.

**Comment by jacguima** [comment]
<img width="299" alt="image" src="https://github.com/user-attachments/assets/c2000c3e-e5b8-43a8-81e0-cae8b4dc2fe7">
com a animação do marca texto. semelhante a esse: https://pin.it/3K1ClLqFl

**Comment by jacguima** [comment]
![Image](https://github.com/user-attachments/assets/36e75d55-8fc9-4421-b33a-332513d7c892)
sim sim, aqui!
