### ISSUE TITLE
rola da plantinha ficar maior?

### ISSUE THREAD

**Issue by jacguima** [jacguima/jacqueline-guimaraes#29]
<img width="84" alt="image" src="https://github.com/user-attachments/assets/f8410fff-91fb-4ebf-a39a-b9b9814e4509">

**Comment by jacguima** [comment]
talvez de outra cor

**Comment by mauricio-azevedo** [comment]
Rola. Isso depende só da imagem que você me mandar. Faz os ajustes que quiser no canva e me manda nos tamanhos 512x512px e uma 192x192px, que eu só substituo lá.

**Comment by jacguima** [comment]
beleza, vou mandar por email.

**Comment by jacguima** [comment]
oie, mandei no seu email!

**Comment by mauricio-azevedo** [comment]
Aumentou bem pouco, tava quase no máximo
