### ISSUE TITLE
Texto sobre atendimento online mobile

### ISSUE THREAD

**Issue by mauricio-azevedo** [jacguima/jacqueline-guimaraes#33]
Você vai querer na versão mobile algo semelhante ao que você mostrou [nessa task](https://github.com/users/jacguima/projects/3/views/1?pane=issue&itemId=85236831&issue=jacguima%7Cjacqueline-guimaraes%7C25)?

**Comment by jacguima** [comment]
ahamm aqui 
<img width="197" alt="image" src="https://github.com/user-attachments/assets/954cec9d-bab5-4abf-8765-39cc93ccc383">

**Comment by jacguima** [comment]
rola de o texto estar na cor verde assim:
<img width="404" alt="image" src="https://github.com/user-attachments/assets/fda3636b-f9f9-4afb-b49b-39c9dbd163aa">

ai quando o marca terto passar ficar assim: 
<img width="293" alt="image" src="https://github.com/user-attachments/assets/6c356cc6-3424-4237-ade3-203d32b7685b">

não sei se fica bom também
